// 第一批官方 Skill 种子数据（格物 Skill Spec v1：system + user 双段）
import { SKILL_COMPLIANCE_REVIEWER_SKILL } from '../lib/skillComplianceReview'

export interface SeedSkill {
  slug: string
  title: string
  description: string
  category: string // 对应 SKILL_CATEGORIES 的 slug
  essential?: boolean
  essentialReason?: string
  featured?: boolean
  systemPrompt: string // Spec prompt.system
  promptTemplate: string // Spec prompt.user_template（含 {{变量}}）
  license?: string
  inputSchema: Record<string, any>
  outputSchema: Record<string, any>
  recommendedModels: { cloud: string[]; local: string[] }
  routePolicy: { default: string; strategies: Record<string, string[]> }
  examples?: Array<{ input: Record<string, any>; output: any }>
}

// 平台代付默认只使用已备案国产白名单模型；境外模型留给用户 BYOK，不进入官方冷启动种子。
const M = {
  deepseek: 'deepseek-chat',
  reasoner: 'deepseek-reasoner',
  qwenPlus: 'qwen-plus',
  qwenTurbo: 'qwen-turbo',
  glm: 'glm-4',
  glmFlash: 'glm-4-flash',
  kimi: 'kimi-k2',
  moonshot: 'moonshot-v1-8k',
}

const CLOUD = { cloud: [M.deepseek, M.qwenPlus, M.kimi], local: ['qwen2.5:14b', 'llama3.1:8b'] }
const LICENSE = 'CC-BY-NC-4.0'

function route(def: string) {
  return {
    default: def,
    strategies: {
      cheap: [M.qwenTurbo, M.glmFlash, M.deepseek],
      quality: [M.reasoner, M.qwenPlus, M.kimi],
      fast: [M.qwenTurbo, M.glmFlash, M.deepseek],
      balanced: [M.deepseek, M.qwenPlus, M.kimi],
      fallback: [M.deepseek, M.qwenPlus, M.qwenTurbo],
    },
  }
}

export const SEED_SKILLS: SeedSkill[] = [
  SKILL_COMPLIANCE_REVIEWER_SKILL,
  {
    slug: 'xhs-title-generator',
    title: '小红书标题生成器',
    description: '根据主题、人群与风格，一键生成 10 个高点击小红书标题。',
    category: 'content-creation',
    essential: true,
    essentialReason: '输入一个主题就能立刻看到 10 个可用标题，反馈最直观，适合第一跑。',
    featured: true,
    license: LICENSE,
    systemPrompt: '你是一名资深小红书内容编辑，擅长写有点击欲、不违规的标题。',
    promptTemplate: [
      '请根据以下信息生成 10 个小红书标题：',
      '主题：{{topic}}',
      '目标人群：{{audience}}',
      '风格：{{style}}',
      '',
      '要求：标题口语化、有点击欲、可含 emoji；避免夸大与违规表述。',
      '请只返回 JSON，形如 {"titles": ["...", "..."], "reason": "选题说明"}。',
    ].join('\n'),
    inputSchema: {
      topic: { type: 'string', label: '主题', required: true, placeholder: '如：秋季护肤' },
      audience: { type: 'string', label: '目标人群', required: false, placeholder: '如：25-30 岁职场女性' },
      style: {
        type: 'select',
        label: '风格',
        required: false,
        options: ['温暖', '犀利', '专业', '情绪共鸣'],
      },
    },
    outputSchema: {
      titles: { type: 'array', item_type: 'string' },
      reason: { type: 'string' },
    },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [
      {
        input: { topic: '秋季护肤', audience: '30岁女性', style: '专业' },
        output: { titles: ['秋天护肤别乱来，这3步比贵妇霜更重要'], reason: '突出季节痛点和实用价值' },
      },
    ],
  },
  {
    slug: 'meeting-minutes',
    title: '会议纪要整理',
    description: '把零散的会议记录整理为结构化纪要：议题、结论、待办与负责人。',
    category: 'office',
    essential: true,
    essentialReason: '粘贴零散会议记录即可得到结论和待办，是办公室最高频、最容易复用的场景。',
    featured: true,
    license: LICENSE,
    systemPrompt: '你是一名专业的会议秘书，善于把零散记录整理成规范纪要。',
    promptTemplate: [
      '请把下面的会议记录整理为规范纪要。',
      '会议主题：{{topic}}',
      '原始记录：',
      '{{notes}}',
      '',
      '请只返回 JSON，形如 {"summary":"一句话总结","decisions":["..."],"todos":[{"task":"...","owner":"...","due":"..."}]}。',
    ].join('\n'),
    inputSchema: {
      topic: { type: 'string', label: '会议主题', required: false },
      notes: { type: 'text', label: '原始记录', required: true, placeholder: '粘贴会议中的零散记录…' },
    },
    outputSchema: {
      summary: { type: 'string' },
      decisions: { type: 'array', item_type: 'string' },
      todos: { type: 'array' },
    },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [
      {
        input: { topic: '周会', notes: '小张说登录页要改；下周一上线；老王负责后端。' },
        output: {
          summary: '确认登录页改版并定档下周一上线',
          decisions: ['登录页改版'],
          todos: [{ task: '后端联调', owner: '老王', due: '下周一' }],
        },
      },
    ],
  },
  {
    slug: 'email-polish',
    title: '邮件润色',
    description: '把口语化或粗糙的邮件草稿润色为得体、专业的中文商务邮件。',
    category: 'office',
    essential: true,
    essentialReason: '低风险文本润色，输入门槛低，能快速感知不同模型的表达质量。',
    license: LICENSE,
    systemPrompt: '你是一名中文商务沟通专家，擅长把粗糙草稿润色为得体专业的邮件。',
    promptTemplate: [
      '请把以下邮件草稿润色得专业、礼貌、条理清晰，保持原意。',
      '语气：{{tone}}',
      '草稿：',
      '{{draft}}',
      '',
      '直接输出润色后的邮件正文（含称呼与结尾），不要解释。',
    ].join('\n'),
    inputSchema: {
      draft: { type: 'text', label: '邮件草稿', required: true, placeholder: '如：王总，资料我晚点给你，你先看下之前那个版本。' },
      tone: {
        type: 'select',
        label: '语气',
        required: false,
        options: ['正式', '友好', '简洁', '诚恳致歉'],
      },
    },
    outputSchema: {},
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [
      {
        input: { draft: '王总，资料我晚点给你，你先看下之前那个版本。', tone: '正式' },
        output: '王总您好，相关资料我会稍后整理后发送给您。您可以先参考此前版本，如有需要我再进一步补充说明。',
      },
    ],
  },
  {
    slug: 'weekly-report',
    title: '周报生成',
    description: '根据本周要点与下周计划，自动生成结构清晰的工作周报。',
    category: 'office',
    essential: true,
    essentialReason: '把零散要点变成结构化周报，适合每周重复使用，台账价值会持续累积。',
    license: LICENSE,
    systemPrompt: '你是一名职场写作助手，擅长把零散要点整理成条理清晰的周报。',
    promptTemplate: [
      '请根据以下要点生成一份条理清晰的工作周报。',
      '岗位/项目：{{role}}',
      '本周完成：{{done}}',
      '下周计划：{{plan}}',
      '',
      '请只返回 JSON，形如 {"thisWeek":["..."],"nextWeek":["..."],"risks":["..."]}。',
    ].join('\n'),
    inputSchema: {
      role: { type: 'string', label: '岗位/项目', required: false, placeholder: '如：产品经理 / 格物 控制台' },
      done: { type: 'text', label: '本周完成要点', required: true, placeholder: '如：完成 Skill 市场必备入口；补充 Passport 证据展示；修复台账筛选。' },
      plan: { type: 'text', label: '下周计划要点', required: false, placeholder: '如：完善企业 Registry 审批；补充失败库 Adapter 复验。' },
    },
    outputSchema: {
      thisWeek: { type: 'array', item_type: 'string' },
      nextWeek: { type: 'array', item_type: 'string' },
      risks: { type: 'array', item_type: 'string' },
    },
    recommendedModels: CLOUD,
    routePolicy: route('cheap'),
    examples: [
      {
        input: {
          role: '产品经理 / 格物 控制台',
          done: '完成 Skill 市场必备入口；补充 Passport 证据展示；修复台账筛选。',
          plan: '完善企业 Registry 审批；补充失败库 Adapter 复验。',
        },
        output: {
          thisWeek: ['完成 Skill 市场必备入口', '补充 Passport 证据展示', '修复台账筛选'],
          nextWeek: ['完善企业 Registry 审批', '补充失败库 Adapter 复验'],
          risks: [],
        },
      },
    ],
  },
  {
    slug: 'bad-review-reply',
    title: '差评回复',
    description: '针对用户差评生成真诚、专业、可平息情绪的客服回复建议。',
    category: 'customer-service',
    essential: true,
    essentialReason: '客服场景边界清晰，容易比较模型语气、稳定性和是否真正解决问题。',
    featured: true,
    license: LICENSE,
    systemPrompt: '你是一名经验丰富的客服主管，回复真诚、不甩锅、给出具体方案。',
    promptTemplate: [
      '请针对下面的差评，给出 3 条不同风格的回复建议。',
      '商品/服务：{{product}}',
      '用户差评：{{review}}',
      '',
      '要求：真诚、不甩锅、给出具体解决方案；避免模板化套话。',
      '请只返回 JSON，形如 {"replies":["...","...","..."]}。',
    ].join('\n'),
    inputSchema: {
      product: { type: 'string', label: '商品/服务', required: false },
      review: { type: 'text', label: '用户差评内容', required: true },
    },
    outputSchema: {
      replies: { type: 'array', item_type: 'string' },
    },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [
      {
        input: { product: '无线耳机', review: '用了三天右耳就没声音了' },
        output: { replies: ['非常抱歉…立即为您换新或退款，请告知订单号。'] },
      },
    ],
  },
  {
    slug: 'zhihu-answer-outline',
    title: '知乎回答提纲',
    description: '把问题拆成观点、论据、案例和结尾，适合经验型长回答。',
    category: 'content-creation',
    license: LICENSE,
    systemPrompt: '你是一名中文长内容策划，擅长把问题拆成有说服力的回答结构。',
    promptTemplate: ['请为知乎问题生成回答提纲。', '问题：{{question}}', '立场：{{stance}}', '请只返回 JSON，形如 {"thesis":"...","outline":["..."],"examples":["..."]}。'].join('\n'),
    inputSchema: { question: { type: 'string', label: '问题', required: true }, stance: { type: 'string', label: '立场', required: false } },
    outputSchema: { thesis: { type: 'string' }, outline: { type: 'array' }, examples: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [{ input: { question: '普通人如何提高长期执行力？', stance: '反对鸡血' }, output: { thesis: '执行力来自环境设计而非意志力', outline: ['定义问题', '拆行动', '设反馈'], examples: ['运动打卡'] } }],
  },
  {
    slug: 'douyin-script-30s',
    title: '30 秒短视频脚本',
    description: '按钩子、冲突、信息点、转化动作生成短视频口播脚本。',
    category: 'content-creation',
    featured: true,
    license: LICENSE,
    systemPrompt: '你是一名短视频编导，脚本要口语、快节奏、能落地拍摄。',
    promptTemplate: ['请生成 30 秒短视频脚本。', '主题：{{topic}}', '受众：{{audience}}', '目标：{{goal}}', '返回 JSON：{"hook":"...","script":["..."],"cta":"..."}。'].join('\n'),
    inputSchema: { topic: { type: 'string', label: '主题', required: true }, audience: { type: 'string', label: '受众' }, goal: { type: 'string', label: '目标' } },
    outputSchema: { hook: { type: 'string' }, script: { type: 'array' }, cta: { type: 'string' } },
    recommendedModels: CLOUD,
    routePolicy: route('fast'),
    examples: [{ input: { topic: '通勤早餐', audience: '上班族', goal: '收藏' }, output: { hook: '别再空腹赶地铁了', script: ['3分钟准备', '两种搭配', '避坑提醒'], cta: '收藏明早照做' } }],
  },
  {
    slug: 'wechat-post-outline',
    title: '公众号文章大纲',
    description: '根据主题生成适合公众号的标题、结构和小节要点。',
    category: 'content-creation',
    license: LICENSE,
    systemPrompt: '你是一名公众号编辑，重视结构、转折和可读性。',
    promptTemplate: ['请为公众号文章生成大纲。', '主题：{{topic}}', '读者：{{audience}}', '请返回 JSON：{"title":"...","sections":[{"heading":"...","points":["..."]}]}。'].join('\n'),
    inputSchema: { topic: { type: 'string', label: '主题', required: true }, audience: { type: 'string', label: '读者' } },
    outputSchema: { title: { type: 'string' }, sections: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [{ input: { topic: 'AI 工具改变普通人的工作流', audience: '职场新人' }, output: { title: '别急着学工具，先改工作流', sections: [{ heading: '为什么', points: ['重复劳动', '反馈变快'] }] } }],
  },
  {
    slug: 'seo-keyword-cluster',
    title: 'SEO 关键词分组',
    description: '把关键词按搜索意图分组，并给出页面类型建议。',
    category: 'content-creation',
    license: LICENSE,
    systemPrompt: '你是一名 SEO 策略师，按搜索意图而不是表面词形分组。',
    promptTemplate: ['请对关键词分组。', '关键词：{{keywords}}', '业务：{{business}}', '返回 JSON：{"clusters":[{"intent":"...","keywords":["..."],"pageType":"..."}]}。'].join('\n'),
    inputSchema: { keywords: { type: 'text', label: '关键词', required: true }, business: { type: 'string', label: '业务' } },
    outputSchema: { clusters: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [{ input: { keywords: 'AI写作工具, AI写作哪个好, 免费AI写作', business: 'SaaS' }, output: { clusters: [{ intent: '选型', keywords: ['AI写作哪个好'], pageType: '对比页' }] } }],
  },
  {
    slug: 'prd-user-story',
    title: 'PRD 用户故事拆解',
    description: '把需求描述拆成用户故事、验收条件和边界情况。',
    category: 'office',
    featured: true,
    license: LICENSE,
    systemPrompt: '你是一名产品经理，输出要可给设计和研发直接评审。',
    promptTemplate: ['请拆解以下需求。', '需求：{{requirement}}', '返回 JSON：{"stories":["..."],"acceptance":["..."],"edgeCases":["..."]}。'].join('\n'),
    inputSchema: { requirement: { type: 'text', label: '需求', required: true } },
    outputSchema: { stories: { type: 'array' }, acceptance: { type: 'array' }, edgeCases: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [{ input: { requirement: '用户可以收藏 Skill，并在控制台查看' }, output: { stories: ['作为用户我想收藏常用 Skill'], acceptance: ['收藏后出现在控制台'], edgeCases: ['重复点击'] } }],
  },
  {
    slug: 'bug-report-normalizer',
    title: 'Bug 报告规范化',
    description: '把口语化问题描述整理为复现步骤、期望结果、实际结果和线索。',
    category: 'code',
    license: LICENSE,
    systemPrompt: '你是一名 QA 工程师，重视可复现、可定位和最小信息集。',
    promptTemplate: ['请规范化 Bug 报告。', '原始描述：{{raw}}', '返回 JSON：{"summary":"...","steps":["..."],"expected":"...","actual":"...","clues":["..."]}。'].join('\n'),
    inputSchema: { raw: { type: 'text', label: '原始描述', required: true } },
    outputSchema: { summary: { type: 'string' }, steps: { type: 'array' }, expected: { type: 'string' }, actual: { type: 'string' }, clues: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [{ input: { raw: '点收藏有时候没反应，刷新又有了' }, output: { summary: '收藏状态反馈不稳定', steps: ['打开详情页', '点击收藏'], expected: '立即反馈', actual: '偶发无反馈', clues: ['可能是竞态或缓存'] } }],
  },
  {
    slug: 'sql-review-checklist',
    title: 'SQL 审查清单',
    description: '根据 SQL 片段生成索引、锁、慢查询和数据安全审查点。',
    category: 'code',
    license: LICENSE,
    systemPrompt: '你是一名数据库审查专家，输出风险和修改建议，不执行 SQL。',
    promptTemplate: ['请审查 SQL：', '{{sql}}', '返回 JSON：{"risks":["..."],"indexes":["..."],"rewrite":"..."}。'].join('\n'),
    inputSchema: { sql: { type: 'text', label: 'SQL', required: true } },
    outputSchema: { risks: { type: 'array' }, indexes: { type: 'array' }, rewrite: { type: 'string' } },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [{ input: { sql: 'select * from orders where user_id=? order by created_at desc' }, output: { risks: ['select *'], indexes: ['(user_id, created_at)'], rewrite: 'select needed columns ...' } }],
  },
  {
    slug: 'incident-review',
    title: '故障复盘初稿',
    description: '把时间线和影响整理为事故复盘：影响、根因、处置、改进项。',
    category: 'office',
    license: LICENSE,
    systemPrompt: '你是一名 SRE 复盘主持人，避免甩锅，强调事实和可执行改进。',
    promptTemplate: ['请整理故障复盘。', '时间线：{{timeline}}', '影响：{{impact}}', '返回 JSON：{"summary":"...","rootCause":"...","actions":["..."],"preventions":["..."]}。'].join('\n'),
    inputSchema: { timeline: { type: 'text', label: '时间线', required: true }, impact: { type: 'text', label: '影响' } },
    outputSchema: { summary: { type: 'string' }, rootCause: { type: 'string' }, actions: { type: 'array' }, preventions: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [{ input: { timeline: '10:00 报错，10:15 回滚', impact: '注册失败' }, output: { summary: '注册链路短暂不可用', rootCause: '发布引入异常', actions: ['回滚'], preventions: ['加回归测试'] } }],
  },
  {
    slug: 'sales-objection-reply',
    title: '销售异议回复',
    description: '针对价格、信任、竞品等异议生成可落地的销售回复。',
    category: 'customer-service',
    license: LICENSE,
    systemPrompt: '你是一名 B2B 销售教练，回复要具体、真诚、不夸大。',
    promptTemplate: ['请回复客户异议。', '产品：{{product}}', '异议：{{objection}}', '返回 JSON：{"reply":"...","followUpQuestions":["..."]}。'].join('\n'),
    inputSchema: { product: { type: 'string', label: '产品' }, objection: { type: 'text', label: '异议', required: true } },
    outputSchema: { reply: { type: 'string' }, followUpQuestions: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [{ input: { product: 'AI Skill 市场', objection: '太贵了' }, output: { reply: '可以先按高频场景试跑，看节省时间是否覆盖成本。', followUpQuestions: ['目前最耗时的流程是什么？'] } }],
  },
  {
    slug: 'customer-faq-draft',
    title: '客服 FAQ 草稿',
    description: '根据产品说明自动生成 FAQ 问答，降低重复客服成本。',
    category: 'customer-service',
    license: LICENSE,
    systemPrompt: '你是一名客服知识库编辑，问答要清楚、可直接发布。',
    promptTemplate: ['请生成 FAQ。', '产品说明：{{description}}', '返回 JSON：{"faqs":[{"q":"...","a":"..."}]}。'].join('\n'),
    inputSchema: { description: { type: 'text', label: '产品说明', required: true } },
    outputSchema: { faqs: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('cheap'),
    examples: [{ input: { description: '邀请制注册，绑定 Key 可免平台扣费' }, output: { faqs: [{ q: '没有邀请码能注册吗？', a: '暂不支持，需要现有用户邀请。' }] } }],
  },
  {
    slug: 'rubric-grader',
    title: '评分 Rubric 生成器',
    description: '为评测任务生成维度、权重和扣分标准。',
    category: 'evaluation',
    featured: true,
    license: LICENSE,
    systemPrompt: '你是一名评测设计专家，rubric 要可复核、可执行、低主观。',
    promptTemplate: ['请为任务生成评分 rubric。', '任务：{{task}}', '返回 JSON：{"dimensions":[{"name":"...","weight":0.0,"criteria":["..."]}]}。'].join('\n'),
    inputSchema: { task: { type: 'text', label: '任务', required: true } },
    outputSchema: { dimensions: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [{ input: { task: '判断模型是否按 JSON schema 输出' }, output: { dimensions: [{ name: '格式有效', weight: 0.5, criteria: ['可解析 JSON', '字段完整'] }] } }],
  },
  {
    slug: 'model-failure-classifier',
    title: '模型失败类型归因',
    description: '把失败输出归类为格式、事实、拒答、截断、指令遗漏等类型。',
    category: 'evaluation',
    license: LICENSE,
    systemPrompt: '你是一名 LLM 评测员，只做归因和复验建议，不捏造事实。',
    promptTemplate: ['请分析模型失败类型。', '期望：{{expected}}', '实际输出：{{actual}}', '返回 JSON：{"errorType":"...","evidence":"...","retryAdvice":"..."}。'].join('\n'),
    inputSchema: { expected: { type: 'text', label: '期望', required: true }, actual: { type: 'text', label: '实际输出', required: true } },
    outputSchema: { errorType: { type: 'string' }, evidence: { type: 'string' }, retryAdvice: { type: 'string' } },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [{ input: { expected: '返回 JSON', actual: '这里是一段自然语言' }, output: { errorType: 'format', evidence: '未返回 JSON', retryAdvice: '加强格式约束并加 schema' } }],
  },
  {
    slug: 'lesson-plan-45min',
    title: '45 分钟课程设计',
    description: '按目标、导入、活动、练习、反馈生成一节课教案。',
    category: 'education',
    license: LICENSE,
    systemPrompt: '你是一名教学设计师，教案要有互动和可观察目标。',
    promptTemplate: ['请设计 45 分钟课程。', '主题：{{topic}}', '学生：{{students}}', '返回 JSON：{"objectives":["..."],"steps":[{"minute":"...","activity":"..."}],"assessment":"..."}。'].join('\n'),
    inputSchema: { topic: { type: 'string', label: '主题', required: true }, students: { type: 'string', label: '学生情况' } },
    outputSchema: { objectives: { type: 'array' }, steps: { type: 'array' }, assessment: { type: 'string' } },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [{ input: { topic: '分数加减法', students: '小学五年级' }, output: { objectives: ['会通分'], steps: [{ minute: '0-5', activity: '情境导入' }], assessment: '出口题' } }],
  },
  {
    slug: 'parent-communication',
    title: '家校沟通措辞',
    description: '把老师想表达的问题改写成克制、具体、可合作的家校沟通话术。',
    category: 'education',
    license: LICENSE,
    systemPrompt: '你是一名班主任沟通顾问，语气尊重，不贴标签，给出合作建议。',
    promptTemplate: ['请改写家校沟通话术。', '原话：{{draft}}', '场景：{{context}}', '直接返回改写后的消息和一句沟通提醒。'].join('\n'),
    inputSchema: { draft: { type: 'text', label: '原话', required: true }, context: { type: 'string', label: '场景' } },
    outputSchema: { message: { type: 'string' }, tip: { type: 'string' } },
    recommendedModels: CLOUD,
    routePolicy: route('quality'),
    examples: [{ input: { draft: '孩子上课总走神，家里管一管', context: '期中后' }, output: { message: '最近观察到孩子课堂专注会有波动...', tip: '先描述事实再提合作' } }],
  },
  {
    slug: 'code-comment-polish',
    title: '代码注释润色',
    description: '把啰嗦或含糊的代码注释改成说明意图、边界和原因的简洁注释。',
    category: 'code',
    license: LICENSE,
    systemPrompt: '你是一名代码审查员，只保留解释意图和边界的注释，删除废话。',
    promptTemplate: ['请润色代码注释。', '语言：{{language}}', '代码：{{code}}', '返回 JSON：{"rewritten":"...","notes":["..."]}。'].join('\n'),
    inputSchema: { language: { type: 'string', label: '语言' }, code: { type: 'text', label: '代码', required: true } },
    outputSchema: { rewritten: { type: 'string' }, notes: { type: 'array' } },
    recommendedModels: CLOUD,
    routePolicy: route('cheap'),
    examples: [{ input: { language: 'TypeScript', code: '// 设置 x 为 1\nconst x=1' }, output: { rewritten: 'const x = 1', notes: ['删除无信息量注释'] } }],
  },
  {
    slug: 'api-error-explainer',
    title: 'API 报错解释器',
    description: '把接口报错、状态码和响应体转成可能原因与下一步排查动作。',
    category: 'code',
    featured: true,
    license: LICENSE,
    systemPrompt: '你是一名后端排障助手，优先给可验证假设和下一步命令。',
    promptTemplate: ['请分析 API 报错。', '请求信息：{{request}}', '响应/日志：{{error}}', '返回 JSON：{"likelyCauses":["..."],"nextChecks":["..."],"userMessage":"..."}。'].join('\n'),
    inputSchema: { request: { type: 'text', label: '请求信息' }, error: { type: 'text', label: '响应/日志', required: true } },
    outputSchema: { likelyCauses: { type: 'array' }, nextChecks: { type: 'array' }, userMessage: { type: 'string' } },
    recommendedModels: CLOUD,
    routePolicy: route('balanced'),
    examples: [{ input: { request: 'POST /v1/skills/run', error: '401 unauthorized' }, output: { likelyCauses: ['Key 无效或缺失'], nextChecks: ['检查 Authorization header'], userMessage: '请重新登录或检查 Key' } }],
  },
]
