/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    skills: Skill;
    'skill-versions': SkillVersion;
    'skill-artifacts': SkillArtifact;
    categories: Category;
    'skill-runs': SkillRun;
    bounties: Bounty;
    'compat-reports': CompatReport;
    users: User;
    'invite-codes': InviteCode;
    'contribution-logs': ContributionLog;
    'contribution-rules': ContributionRule;
    'credit-logs': CreditLog;
    favorites: Favorite;
    'runner-clients': RunnerClient;
    'device-codes': DeviceCode;
    'skill-installs': SkillInstall;
    notifications: Notification;
    reviews: Review;
    reports: Report;
    media: Media;
    'model-price-snapshots': ModelPriceSnapshot;
    'score-snapshots': ScoreSnapshot;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'skill-versions': SkillVersionsSelect<false> | SkillVersionsSelect<true>;
    'skill-artifacts': SkillArtifactsSelect<false> | SkillArtifactsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'skill-runs': SkillRunsSelect<false> | SkillRunsSelect<true>;
    bounties: BountiesSelect<false> | BountiesSelect<true>;
    'compat-reports': CompatReportsSelect<false> | CompatReportsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'invite-codes': InviteCodesSelect<false> | InviteCodesSelect<true>;
    'contribution-logs': ContributionLogsSelect<false> | ContributionLogsSelect<true>;
    'contribution-rules': ContributionRulesSelect<false> | ContributionRulesSelect<true>;
    'credit-logs': CreditLogsSelect<false> | CreditLogsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'runner-clients': RunnerClientsSelect<false> | RunnerClientsSelect<true>;
    'device-codes': DeviceCodesSelect<false> | DeviceCodesSelect<true>;
    'skill-installs': SkillInstallsSelect<false> | SkillInstallsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'model-price-snapshots': ModelPriceSnapshotsSelect<false> | ModelPriceSnapshotsSelect<true>;
    'score-snapshots': ScoreSnapshotsSelect<false> | ScoreSnapshotsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'economy-settings': EconomySetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'economy-settings': EconomySettingsSelect<false> | EconomySettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  title: string;
  slug?: string | null;
  description?: string | null;
  category?: (string | null) | Category;
  author?: (string | null) | User;
  visibility?: ('public' | 'private' | 'unlisted' | 'enterprise') | null;
  status?: ('draft' | 'pending' | 'published' | 'rejected' | 'archived') | null;
  currentVersion?: (string | null) | SkillVersion;
  isOfficial?: boolean | null;
  isFeatured?: boolean | null;
  isFreeleech?: boolean | null;
  skillRank?: number | null;
  localScore?: number | null;
  healthScore?: number | null;
  runCount?: number | null;
  downloadCount?: number | null;
  favoriteCount?: number | null;
  reviewCount?: number | null;
  avgRating?: number | null;
  avgCost?: number | null;
  avgLatencyMs?: number | null;
  successRate?: number | null;
  formatSuccessRate?: number | null;
  lastRunAt?: string | null;
  lastUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  description?: string | null;
  icon?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  role: 'user' | 'creator' | 'certified_creator' | 'reviewer' | 'admin' | 'enterprise_admin';
  level?: number | null;
  /**
   * banned = 禁止登录且冻结一切经济操作（挣分/兑换/运行）
   */
  accountStatus?: ('active' | 'banned') | null;
  contributionScore?: number | null;
  consumptionScore?: number | null;
  /**
   * 1 credit = ¥0.01 零售。权威值，恒等于 credit-logs 之和；仅服务端事务写入
   */
  creditBalance?: number | null;
  ratioScore?: number | null;
  inviteCount?: number | null;
  warningCount?: number | null;
  bio?: string | null;
  invitedBy?: (string | null) | User;
  ipHash?: string | null;
  newapiUserId?: string | null;
  /**
   * MVP 阶段服务端保存；生产需加密存储
   */
  newapiKeyEncrypted?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions".
 */
export interface SkillVersion {
  id: string;
  skill: string | Skill;
  version: string;
  /**
   * Spec v1 的 prompt.system；可空
   */
  systemPrompt?: string | null;
  /**
   * Spec v1 的 prompt.user_template；支持 {{变量名}} 占位符
   */
  promptTemplate: string;
  /**
   * 形如 {"topic":{"type":"string","label":"主题","required":true}}
   */
  inputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 形如 {"cloud":["deepseek-chat"],"local":["qwen2.5:14b"]}
   */
  recommendedModels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 形如 {"default":"balanced","strategies":{"cheap":[...],"quality":[...],"fallback":[...]}}
   */
  routePolicy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  changelog?: string | null;
  license?: string | null;
  minRunnerVersion?: string | null;
  permissions?: {
    network?: boolean | null;
    fileRead?: boolean | null;
    fileWrite?: boolean | null;
    shell?: boolean | null;
  };
  /**
   * 形如 [{"input":{...},"output":{...}}]
   */
  examples?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'active' | 'deprecated') | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * 发布时冻结的不可变 manifest 快照（系统生成，请勿手改）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-artifacts".
 */
export interface SkillArtifact {
  id: string;
  skill: string | Skill;
  skillVersion: string | SkillVersion;
  version?: string | null;
  format: 'yaml' | 'json';
  manifest?: string | null;
  checksum?: string | null;
  fileSize?: number | null;
  downloadCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-runs".
 */
export interface SkillRun {
  id: string;
  runId?: string | null;
  user?: (string | null) | User;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  model?: string | null;
  routeMode?: ('cheap' | 'quality' | 'fast' | 'balanced') | null;
  inputJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputText?: string | null;
  outputJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  promptTokens?: number | null;
  completionTokens?: number | null;
  totalTokens?: number | null;
  estimatedCost?: number | null;
  chargedAmount?: number | null;
  /**
   * 相比默认premium模型省下的估算金额(省钱路由的累计价值)
   */
  savedAmount?: number | null;
  latencyMs?: number | null;
  success?: boolean | null;
  errorCode?: string | null;
  formatValid?: boolean | null;
  /**
   * 对比/探测运行(skipAggregate)为 false，不计入 headline 指标，台账对账据此过滤
   */
  countedInMetrics?: boolean | null;
  newapiLogId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bounties".
 */
export interface Bounty {
  id: string;
  title: string;
  description?: string | null;
  creator?: (string | null) | User;
  rewardType?: ('points' | 'cash' | 'credit') | null;
  rewardPoints?: number | null;
  rewardAmount?: number | null;
  status?: ('open' | 'accepted' | 'submitted' | 'completed' | 'disputed' | 'cancelled') | null;
  /**
   * 发布时从发布人冻结，完成后发给接单人
   */
  frozenPoints?: number | null;
  /**
   * 幂等键：防止重复提交导致重复发布/扣款
   */
  idempotencyKey?: string | null;
  acceptedBy?: (string | null) | User;
  submittedSkill?: (string | null) | Skill;
  requirements?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dueAt?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 本地模型兼容报告（系统接收，不含输入/输出原文）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compat-reports".
 */
export interface CompatReport {
  id: string;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  runner?: (string | null) | RunnerClient;
  anonymousUserHash?: string | null;
  modelProvider?: string | null;
  modelName?: string | null;
  modelVersion?: string | null;
  success?: boolean | null;
  latencyMs?: number | null;
  formatValid?: boolean | null;
  errorType?: string | null;
  inputSizeBucket?: string | null;
  outputSizeBucket?: string | null;
  runnerVersion?: string | null;
  source?: ('community' | 'verified' | 'online' | 'benchmark') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runner-clients".
 */
export interface RunnerClient {
  id: string;
  user: string | User;
  runnerId: string;
  token?: string | null;
  runnerVersion?: string | null;
  os?: string | null;
  arch?: string | null;
  label?: string | null;
  anonymousMode?: boolean | null;
  trustedLevel?: ('community' | 'verified') | null;
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes".
 */
export interface InviteCode {
  id: string;
  code?: string | null;
  inviter?: (string | null) | User;
  usedBy?: (string | null) | User;
  status?: ('unused' | 'used' | 'expired' | 'revoked') | null;
  minLevelRequired?: number | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-logs".
 */
export interface ContributionLog {
  id: string;
  user: string | User;
  actionType:
    | 'skill_published'
    | 'skill_favorited'
    | 'skill_run'
    | 'skill_high_rating'
    | 'skill_version_update'
    | 'fix_issue'
    | 'eval_sample'
    | 'failure_case'
    | 'route_optimization'
    | 'compat_report'
    | 'review'
    | 'security'
    | 'bounty'
    | 'invite'
    | 'consume'
    | 'other';
  points: number;
  /**
   * 引发本次发放的用户（如收藏者/调用者），用于一次性奖励幂等去重
   */
  actor?: (string | null) | User;
  idempotencyKey?: string | null;
  relatedSkill?: (string | null) | Skill;
  relatedBounty?: (string | null) | Bounty;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-rules".
 */
export interface ContributionRule {
  id: string;
  actionType:
    | 'skill_published'
    | 'skill_favorited'
    | 'skill_run'
    | 'skill_high_rating'
    | 'skill_version_update'
    | 'fix_issue'
    | 'eval_sample'
    | 'failure_case'
    | 'route_optimization'
    | 'compat_report'
    | 'review'
    | 'security'
    | 'bounty'
    | 'invite'
    | 'consume'
    | 'other';
  basePoints: number;
  /**
   * 每用户每日该行为发放次数上限，0=不限
   */
  dailyLimit?: number | null;
  selfActionExcluded?: boolean | null;
  enabled?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-logs".
 */
export interface CreditLog {
  id: string;
  user: string | User;
  type: 'recharge' | 'exchange' | 'consume' | 'refund' | 'adjust';
  amount: number;
  balanceAfter?: number | null;
  idempotencyKey?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  user?: (string | null) | User;
  skill: string | Skill;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-codes".
 */
export interface DeviceCode {
  id: string;
  deviceCode: string;
  userCode: string;
  status?: ('pending' | 'authorized' | 'denied' | 'consumed') | null;
  user?: (string | null) | User;
  runnerClient?: (string | null) | RunnerClient;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-installs".
 */
export interface SkillInstall {
  id: string;
  user: string | User;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  runner?: (string | null) | RunnerClient;
  installedVersion?: string | null;
  installedChecksum?: string | null;
  status?: ('installed' | 'removed') | null;
  installedAt?: string | null;
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  user: string | User;
  type?: ('skill_favorited' | 'review' | 'bounty_accepted' | 'bounty_submitted' | 'bounty_completed' | 'system') | null;
  title: string;
  body?: string | null;
  link?: string | null;
  read?: boolean | null;
  relatedSkill?: (string | null) | Skill;
  relatedBounty?: (string | null) | Bounty;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  skill: string | Skill;
  user?: (string | null) | User;
  rating?: number | null;
  content?: string | null;
  type?: ('review' | 'failure_case' | 'compat_report') | null;
  status?: ('visible' | 'hidden' | 'pending') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  reporter?: (string | null) | User;
  targetType: 'skill' | 'review' | 'user' | 'bounty';
  targetId: string;
  reason: 'spam' | 'low_quality' | 'copyright' | 'abuse' | 'security' | 'other';
  detail?: string | null;
  status?: ('open' | 'reviewing' | 'resolved' | 'dismissed') | null;
  handledBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-price-snapshots".
 */
export interface ModelPriceSnapshot {
  id: string;
  model: string;
  inputPrice: number;
  outputPrice: number;
  currency?: string | null;
  sourceUrl?: string | null;
  capturedAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "score-snapshots".
 */
export interface ScoreSnapshot {
  id: string;
  skill: string | Skill;
  localScore: number;
  reportCount?: number | null;
  payloadHash?: string | null;
  keyId?: string | null;
  signature?: string | null;
  signedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'skill-versions';
        value: string | SkillVersion;
      } | null)
    | ({
        relationTo: 'skill-artifacts';
        value: string | SkillArtifact;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'skill-runs';
        value: string | SkillRun;
      } | null)
    | ({
        relationTo: 'bounties';
        value: string | Bounty;
      } | null)
    | ({
        relationTo: 'compat-reports';
        value: string | CompatReport;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'invite-codes';
        value: string | InviteCode;
      } | null)
    | ({
        relationTo: 'contribution-logs';
        value: string | ContributionLog;
      } | null)
    | ({
        relationTo: 'contribution-rules';
        value: string | ContributionRule;
      } | null)
    | ({
        relationTo: 'credit-logs';
        value: string | CreditLog;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'runner-clients';
        value: string | RunnerClient;
      } | null)
    | ({
        relationTo: 'device-codes';
        value: string | DeviceCode;
      } | null)
    | ({
        relationTo: 'skill-installs';
        value: string | SkillInstall;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'model-price-snapshots';
        value: string | ModelPriceSnapshot;
      } | null)
    | ({
        relationTo: 'score-snapshots';
        value: string | ScoreSnapshot;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  author?: T;
  visibility?: T;
  status?: T;
  currentVersion?: T;
  isOfficial?: T;
  isFeatured?: T;
  isFreeleech?: T;
  skillRank?: T;
  localScore?: T;
  healthScore?: T;
  runCount?: T;
  downloadCount?: T;
  favoriteCount?: T;
  reviewCount?: T;
  avgRating?: T;
  avgCost?: T;
  avgLatencyMs?: T;
  successRate?: T;
  formatSuccessRate?: T;
  lastRunAt?: T;
  lastUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions_select".
 */
export interface SkillVersionsSelect<T extends boolean = true> {
  skill?: T;
  version?: T;
  systemPrompt?: T;
  promptTemplate?: T;
  inputSchema?: T;
  outputSchema?: T;
  recommendedModels?: T;
  routePolicy?: T;
  changelog?: T;
  license?: T;
  minRunnerVersion?: T;
  permissions?:
    | T
    | {
        network?: T;
        fileRead?: T;
        fileWrite?: T;
        shell?: T;
      };
  examples?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-artifacts_select".
 */
export interface SkillArtifactsSelect<T extends boolean = true> {
  skill?: T;
  skillVersion?: T;
  version?: T;
  format?: T;
  manifest?: T;
  checksum?: T;
  fileSize?: T;
  downloadCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-runs_select".
 */
export interface SkillRunsSelect<T extends boolean = true> {
  runId?: T;
  user?: T;
  skill?: T;
  skillVersion?: T;
  model?: T;
  routeMode?: T;
  inputJson?: T;
  outputText?: T;
  outputJson?: T;
  promptTokens?: T;
  completionTokens?: T;
  totalTokens?: T;
  estimatedCost?: T;
  chargedAmount?: T;
  savedAmount?: T;
  latencyMs?: T;
  success?: T;
  errorCode?: T;
  formatValid?: T;
  countedInMetrics?: T;
  newapiLogId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bounties_select".
 */
export interface BountiesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  creator?: T;
  rewardType?: T;
  rewardPoints?: T;
  rewardAmount?: T;
  status?: T;
  frozenPoints?: T;
  idempotencyKey?: T;
  acceptedBy?: T;
  submittedSkill?: T;
  requirements?: T;
  dueAt?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compat-reports_select".
 */
export interface CompatReportsSelect<T extends boolean = true> {
  skill?: T;
  skillVersion?: T;
  runner?: T;
  anonymousUserHash?: T;
  modelProvider?: T;
  modelName?: T;
  modelVersion?: T;
  success?: T;
  latencyMs?: T;
  formatValid?: T;
  errorType?: T;
  inputSizeBucket?: T;
  outputSizeBucket?: T;
  runnerVersion?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  role?: T;
  level?: T;
  accountStatus?: T;
  contributionScore?: T;
  consumptionScore?: T;
  creditBalance?: T;
  ratioScore?: T;
  inviteCount?: T;
  warningCount?: T;
  bio?: T;
  invitedBy?: T;
  ipHash?: T;
  newapiUserId?: T;
  newapiKeyEncrypted?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes_select".
 */
export interface InviteCodesSelect<T extends boolean = true> {
  code?: T;
  inviter?: T;
  usedBy?: T;
  status?: T;
  minLevelRequired?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-logs_select".
 */
export interface ContributionLogsSelect<T extends boolean = true> {
  user?: T;
  actionType?: T;
  points?: T;
  actor?: T;
  idempotencyKey?: T;
  relatedSkill?: T;
  relatedBounty?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-rules_select".
 */
export interface ContributionRulesSelect<T extends boolean = true> {
  actionType?: T;
  basePoints?: T;
  dailyLimit?: T;
  selfActionExcluded?: T;
  enabled?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-logs_select".
 */
export interface CreditLogsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  amount?: T;
  balanceAfter?: T;
  idempotencyKey?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  skill?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runner-clients_select".
 */
export interface RunnerClientsSelect<T extends boolean = true> {
  user?: T;
  runnerId?: T;
  token?: T;
  runnerVersion?: T;
  os?: T;
  arch?: T;
  label?: T;
  anonymousMode?: T;
  trustedLevel?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-codes_select".
 */
export interface DeviceCodesSelect<T extends boolean = true> {
  deviceCode?: T;
  userCode?: T;
  status?: T;
  user?: T;
  runnerClient?: T;
  meta?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-installs_select".
 */
export interface SkillInstallsSelect<T extends boolean = true> {
  user?: T;
  skill?: T;
  skillVersion?: T;
  runner?: T;
  installedVersion?: T;
  installedChecksum?: T;
  status?: T;
  installedAt?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  body?: T;
  link?: T;
  read?: T;
  relatedSkill?: T;
  relatedBounty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  skill?: T;
  user?: T;
  rating?: T;
  content?: T;
  type?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  detail?: T;
  status?: T;
  handledBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-price-snapshots_select".
 */
export interface ModelPriceSnapshotsSelect<T extends boolean = true> {
  model?: T;
  inputPrice?: T;
  outputPrice?: T;
  currency?: T;
  sourceUrl?: T;
  capturedAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "score-snapshots_select".
 */
export interface ScoreSnapshotsSelect<T extends boolean = true> {
  skill?: T;
  localScore?: T;
  reportCount?: T;
  payloadHash?: T;
  keyId?: T;
  signature?: T;
  signedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  slogan?: string | null;
  featuredSkills?: (string | Skill)[] | null;
  announcement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-settings".
 */
export interface EconomySetting {
  id: string;
  exchangeEnabled?: boolean | null;
  /**
   * 新用户注册即送的试用额度（营销成本，§7A 建议 30-50）。0=不送。赠送的 credit 只能消耗，不产术值
   */
  freeCreditOnRegister?: number | null;
  alpha?: number | null;
  /**
   * 接入 New API /api/log 自动回填前手动填；0 = 兑换池空、自动关闭兑换。1 分 = 1 credit
   */
  monthlyRealizedMarginCents?: number | null;
  pointsPerCredit?: number | null;
  minCreditPerTx?: number | null;
  perTxMaxCredit?: number | null;
  perUserDailyMaxCredit?: number | null;
  perUserMonthlyMaxCredit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  slogan?: T;
  featuredSkills?: T;
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-settings_select".
 */
export interface EconomySettingsSelect<T extends boolean = true> {
  exchangeEnabled?: T;
  freeCreditOnRegister?: T;
  alpha?: T;
  monthlyRealizedMarginCents?: T;
  pointsPerCredit?: T;
  minCreditPerTx?: T;
  perTxMaxCredit?: T;
  perUserDailyMaxCredit?: T;
  perUserMonthlyMaxCredit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}