/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    skills: Skill;
    'skill-versions': SkillVersion;
    categories: Category;
    'skill-runs': SkillRun;
    bounties: Bounty;
    users: User;
    'invite-codes': InviteCode;
    'contribution-logs': ContributionLog;
    favorites: Favorite;
    reviews: Review;
    reports: Report;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'skill-versions': SkillVersionsSelect<false> | SkillVersionsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'skill-runs': SkillRunsSelect<false> | SkillRunsSelect<true>;
    bounties: BountiesSelect<false> | BountiesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'invite-codes': InviteCodesSelect<false> | InviteCodesSelect<true>;
    'contribution-logs': ContributionLogsSelect<false> | ContributionLogsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  title: string;
  slug?: string | null;
  description?: string | null;
  category?: (string | null) | Category;
  author?: (string | null) | User;
  visibility?: ('public' | 'private' | 'unlisted' | 'enterprise') | null;
  status?: ('draft' | 'pending' | 'published' | 'rejected' | 'archived') | null;
  currentVersion?: (string | null) | SkillVersion;
  isOfficial?: boolean | null;
  isFeatured?: boolean | null;
  isFreeleech?: boolean | null;
  skillRank?: number | null;
  healthScore?: number | null;
  runCount?: number | null;
  downloadCount?: number | null;
  favoriteCount?: number | null;
  reviewCount?: number | null;
  avgRating?: number | null;
  avgCost?: number | null;
  avgLatencyMs?: number | null;
  successRate?: number | null;
  formatSuccessRate?: number | null;
  lastRunAt?: string | null;
  lastUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  description?: string | null;
  icon?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  role: 'user' | 'creator' | 'certified_creator' | 'reviewer' | 'admin' | 'enterprise_admin';
  level?: number | null;
  contributionScore?: number | null;
  consumptionScore?: number | null;
  ratioScore?: number | null;
  inviteCount?: number | null;
  warningCount?: number | null;
  bio?: string | null;
  invitedBy?: (string | null) | User;
  newapiUserId?: string | null;
  /**
   * MVP 阶段服务端保存；生产需加密存储
   */
  newapiKeyEncrypted?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions".
 */
export interface SkillVersion {
  id: string;
  skill: string | Skill;
  version: string;
  /**
   * 支持 {{变量名}} 占位符
   */
  promptTemplate: string;
  /**
   * 形如 {"topic":{"type":"string","label":"主题","required":true}}
   */
  inputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 形如 {"cloud":["deepseek-chat"],"local":["qwen2.5:14b"]}
   */
  recommendedModels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 形如 {"default":"balanced","strategies":{"cheap":[...],"quality":[...],"fallback":[...]}}
   */
  routePolicy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  changelog?: string | null;
  status?: ('draft' | 'active' | 'deprecated') | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-runs".
 */
export interface SkillRun {
  id: string;
  runId?: string | null;
  user?: (string | null) | User;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  model?: string | null;
  routeMode?: ('cheap' | 'quality' | 'fast' | 'balanced') | null;
  inputJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputText?: string | null;
  outputJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  promptTokens?: number | null;
  completionTokens?: number | null;
  totalTokens?: number | null;
  estimatedCost?: number | null;
  chargedAmount?: number | null;
  latencyMs?: number | null;
  success?: boolean | null;
  errorCode?: string | null;
  formatValid?: boolean | null;
  newapiLogId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bounties".
 */
export interface Bounty {
  id: string;
  title: string;
  description?: string | null;
  creator?: (string | null) | User;
  rewardType?: ('points' | 'cash' | 'credit') | null;
  rewardPoints?: number | null;
  rewardAmount?: number | null;
  status?: ('open' | 'accepted' | 'submitted' | 'completed' | 'cancelled') | null;
  acceptedBy?: (string | null) | User;
  submittedSkill?: (string | null) | Skill;
  requirements?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dueAt?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes".
 */
export interface InviteCode {
  id: string;
  code?: string | null;
  inviter?: (string | null) | User;
  usedBy?: (string | null) | User;
  status?: ('unused' | 'used' | 'expired' | 'revoked') | null;
  minLevelRequired?: number | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-logs".
 */
export interface ContributionLog {
  id: string;
  user: string | User;
  actionType:
    | 'skill_published'
    | 'skill_favorited'
    | 'skill_run'
    | 'skill_high_rating'
    | 'skill_version_update'
    | 'fix_issue'
    | 'eval_sample'
    | 'failure_case'
    | 'route_optimization'
    | 'review'
    | 'security'
    | 'bounty'
    | 'invite'
    | 'consume'
    | 'other';
  points: number;
  relatedSkill?: (string | null) | Skill;
  relatedBounty?: (string | null) | Bounty;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  user?: (string | null) | User;
  skill: string | Skill;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  skill: string | Skill;
  user?: (string | null) | User;
  rating?: number | null;
  content?: string | null;
  type?: ('review' | 'failure_case' | 'compat_report') | null;
  status?: ('visible' | 'hidden' | 'pending') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  reporter?: (string | null) | User;
  targetType: 'skill' | 'review' | 'user' | 'bounty';
  targetId: string;
  reason: 'spam' | 'low_quality' | 'copyright' | 'abuse' | 'security' | 'other';
  detail?: string | null;
  status?: ('open' | 'reviewing' | 'resolved' | 'dismissed') | null;
  handledBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'skill-versions';
        value: string | SkillVersion;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'skill-runs';
        value: string | SkillRun;
      } | null)
    | ({
        relationTo: 'bounties';
        value: string | Bounty;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'invite-codes';
        value: string | InviteCode;
      } | null)
    | ({
        relationTo: 'contribution-logs';
        value: string | ContributionLog;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  author?: T;
  visibility?: T;
  status?: T;
  currentVersion?: T;
  isOfficial?: T;
  isFeatured?: T;
  isFreeleech?: T;
  skillRank?: T;
  healthScore?: T;
  runCount?: T;
  downloadCount?: T;
  favoriteCount?: T;
  reviewCount?: T;
  avgRating?: T;
  avgCost?: T;
  avgLatencyMs?: T;
  successRate?: T;
  formatSuccessRate?: T;
  lastRunAt?: T;
  lastUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions_select".
 */
export interface SkillVersionsSelect<T extends boolean = true> {
  skill?: T;
  version?: T;
  promptTemplate?: T;
  inputSchema?: T;
  outputSchema?: T;
  recommendedModels?: T;
  routePolicy?: T;
  changelog?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-runs_select".
 */
export interface SkillRunsSelect<T extends boolean = true> {
  runId?: T;
  user?: T;
  skill?: T;
  skillVersion?: T;
  model?: T;
  routeMode?: T;
  inputJson?: T;
  outputText?: T;
  outputJson?: T;
  promptTokens?: T;
  completionTokens?: T;
  totalTokens?: T;
  estimatedCost?: T;
  chargedAmount?: T;
  latencyMs?: T;
  success?: T;
  errorCode?: T;
  formatValid?: T;
  newapiLogId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bounties_select".
 */
export interface BountiesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  creator?: T;
  rewardType?: T;
  rewardPoints?: T;
  rewardAmount?: T;
  status?: T;
  acceptedBy?: T;
  submittedSkill?: T;
  requirements?: T;
  dueAt?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  role?: T;
  level?: T;
  contributionScore?: T;
  consumptionScore?: T;
  ratioScore?: T;
  inviteCount?: T;
  warningCount?: T;
  bio?: T;
  invitedBy?: T;
  newapiUserId?: T;
  newapiKeyEncrypted?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes_select".
 */
export interface InviteCodesSelect<T extends boolean = true> {
  code?: T;
  inviter?: T;
  usedBy?: T;
  status?: T;
  minLevelRequired?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-logs_select".
 */
export interface ContributionLogsSelect<T extends boolean = true> {
  user?: T;
  actionType?: T;
  points?: T;
  relatedSkill?: T;
  relatedBounty?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  skill?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  skill?: T;
  user?: T;
  rating?: T;
  content?: T;
  type?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  detail?: T;
  status?: T;
  handledBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  slogan?: string | null;
  featuredSkills?: (string | Skill)[] | null;
  announcement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  slogan?: T;
  featuredSkills?: T;
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}