/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    skills: Skill;
    'skill-versions': SkillVersion;
    'skill-passports': SkillPassport;
    'skill-artifacts': SkillArtifact;
    categories: Category;
    'skill-runs': SkillRun;
    bounties: Bounty;
    'compat-reports': CompatReport;
    'compat-test-cases': CompatTestCase;
    'adapter-profiles': AdapterProfile;
    users: User;
    'invite-codes': InviteCode;
    'contribution-logs': ContributionLog;
    'contribution-rules': ContributionRule;
    'credit-logs': CreditLog;
    'recharge-codes': RechargeCode;
    favorites: Favorite;
    'runner-clients': RunnerClient;
    'device-codes': DeviceCode;
    'skill-installs': SkillInstall;
    notifications: Notification;
    reviews: Review;
    reports: Report;
    'failure-cases': FailureCase;
    'evidence-snapshots': EvidenceSnapshot;
    'audit-logs': AuditLog;
    organizations: Organization;
    'organization-members': OrganizationMember;
    'enterprise-registries': EnterpriseRegistry;
    'enterprise-audit-logs': EnterpriseAuditLog;
    media: Media;
    'model-profiles': ModelProfile;
    'model-price-snapshots': ModelPriceSnapshot;
    'score-snapshots': ScoreSnapshot;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'skill-versions': SkillVersionsSelect<false> | SkillVersionsSelect<true>;
    'skill-passports': SkillPassportsSelect<false> | SkillPassportsSelect<true>;
    'skill-artifacts': SkillArtifactsSelect<false> | SkillArtifactsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'skill-runs': SkillRunsSelect<false> | SkillRunsSelect<true>;
    bounties: BountiesSelect<false> | BountiesSelect<true>;
    'compat-reports': CompatReportsSelect<false> | CompatReportsSelect<true>;
    'compat-test-cases': CompatTestCasesSelect<false> | CompatTestCasesSelect<true>;
    'adapter-profiles': AdapterProfilesSelect<false> | AdapterProfilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'invite-codes': InviteCodesSelect<false> | InviteCodesSelect<true>;
    'contribution-logs': ContributionLogsSelect<false> | ContributionLogsSelect<true>;
    'contribution-rules': ContributionRulesSelect<false> | ContributionRulesSelect<true>;
    'credit-logs': CreditLogsSelect<false> | CreditLogsSelect<true>;
    'recharge-codes': RechargeCodesSelect<false> | RechargeCodesSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'runner-clients': RunnerClientsSelect<false> | RunnerClientsSelect<true>;
    'device-codes': DeviceCodesSelect<false> | DeviceCodesSelect<true>;
    'skill-installs': SkillInstallsSelect<false> | SkillInstallsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'failure-cases': FailureCasesSelect<false> | FailureCasesSelect<true>;
    'evidence-snapshots': EvidenceSnapshotsSelect<false> | EvidenceSnapshotsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'organization-members': OrganizationMembersSelect<false> | OrganizationMembersSelect<true>;
    'enterprise-registries': EnterpriseRegistriesSelect<false> | EnterpriseRegistriesSelect<true>;
    'enterprise-audit-logs': EnterpriseAuditLogsSelect<false> | EnterpriseAuditLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'model-profiles': ModelProfilesSelect<false> | ModelProfilesSelect<true>;
    'model-price-snapshots': ModelPriceSnapshotsSelect<false> | ModelPriceSnapshotsSelect<true>;
    'score-snapshots': ScoreSnapshotsSelect<false> | ScoreSnapshotsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'economy-settings': EconomySetting;
    'deployment-settings': DeploymentSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'economy-settings': EconomySettingsSelect<false> | EconomySettingsSelect<true>;
    'deployment-settings': DeploymentSettingsSelect<false> | DeploymentSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  title: string;
  slug?: string | null;
  description?: string | null;
  clientSubmissionKey?: string | null;
  category?: (string | null) | Category;
  importSourceFormat?: string | null;
  importSourceLocator?: string | null;
  importSourceHash?: string | null;
  importSourceLastSyncedAt?: string | null;
  importSourceLastDiff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  author?: (string | null) | User;
  /**
   * 从哪个 Skill 复制而来（血统，用于变异-表现差分分析）
   */
  forkedFrom?: (string | null) | Skill;
  visibility?: ('public' | 'private' | 'unlisted' | 'enterprise') | null;
  status?: ('draft' | 'pending' | 'published' | 'rejected' | 'archived') | null;
  currentVersion?: (string | null) | SkillVersion;
  isOfficial?: boolean | null;
  /**
   * 新用户上手第一屏推荐，强调快速尝到甜头。
   */
  isEssential?: boolean | null;
  /**
   * 解释为什么适合作为新用户第一跑，会展示在首页、市场和公开 API。
   */
  essentialReason?: string | null;
  isFeatured?: boolean | null;
  isFreeleech?: boolean | null;
  skillRank?: number | null;
  localScore?: number | null;
  healthScore?: number | null;
  runCount?: number | null;
  downloadCount?: number | null;
  favoriteCount?: number | null;
  reviewCount?: number | null;
  avgRating?: number | null;
  avgCost?: number | null;
  avgLatencyMs?: number | null;
  successRate?: number | null;
  formatSuccessRate?: number | null;
  lastRunAt?: string | null;
  lastUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  description?: string | null;
  icon?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  role: 'user' | 'creator' | 'certified_creator' | 'reviewer' | 'admin' | 'enterprise_admin';
  level?: number | null;
  /**
   * banned = 禁止登录且冻结一切经济操作（挣分/兑换/运行）
   */
  accountStatus?: ('active' | 'banned') | null;
  /**
   * 权威值，恒等于 contribution-logs 之和；仅服务端事务/对账 worker 写入
   */
  contributionScore?: number | null;
  /**
   * 派生/历史指标，禁止后台手改
   */
  consumptionScore?: number | null;
  /**
   * 1 credit = ¥0.01 零售。权威值，恒等于 credit-logs 之和；仅服务端事务写入
   */
  creditBalance?: number | null;
  ratioScore?: number | null;
  inviteCount?: number | null;
  warningCount?: number | null;
  bio?: string | null;
  invitedBy?: (string | null) | User;
  ipHash?: string | null;
  deviceHash?: string | null;
  newapiUserId?: string | null;
  /**
   * 服务端 AES-GCM 加密存储；仅 /v1/me/settings 可写，不在后台或 REST 回显
   */
  newapiKeyEncrypted?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions".
 */
export interface SkillVersion {
  id: string;
  skill: string | Skill;
  version: string;
  /**
   * Spec v1 的 prompt.system；可空
   */
  systemPrompt?: string | null;
  /**
   * Spec v1 的 prompt.user_template；支持 {{变量名}} 占位符
   */
  promptTemplate: string;
  /**
   * 形如 {"topic":{"type":"string","label":"主题","required":true}}
   */
  inputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 形如 {"cloud":["deepseek-chat"],"local":["qwen2.5:14b"]}
   */
  recommendedModels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 形如 {"default":"balanced","strategies":{"cheap":[...],"quality":[...],"fallback":[...]}}
   */
  routePolicy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  changelog?: string | null;
  contractHash?: string | null;
  contractStatus?: ('initial' | 'compatible_change' | 'breaking_change') | null;
  license?: string | null;
  minRunnerVersion?: string | null;
  permissions?: {
    network?: boolean | null;
    fileRead?: boolean | null;
    fileWrite?: boolean | null;
    shell?: boolean | null;
  };
  /**
   * 形如 [{"input":{...},"output":{...}}]
   */
  examples?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'active' | 'deprecated') | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Skill 的身份、签名、兼容证据、失败记录与治理状态。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-passports".
 */
export interface SkillPassport {
  id: string;
  title: string;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  status?: ('draft' | 'current' | 'stale' | 'revoked') | null;
  skillClass?: ('verified' | 'imported' | 'high_risk' | 'rejected') | null;
  trustScore?: number | null;
  signatureStatus?: string | null;
  manifestChecksum?: string | null;
  capabilitySummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  compatibilitySummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reliabilitySummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  safetySummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  failureSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  evidenceSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  evidenceHash?: string | null;
  enterpriseSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 发布时冻结的不可变 manifest 快照（系统生成，请勿手改）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-artifacts".
 */
export interface SkillArtifact {
  id: string;
  skill: string | Skill;
  skillVersion: string | SkillVersion;
  version?: string | null;
  format: 'yaml' | 'json';
  manifest?: string | null;
  checksum?: string | null;
  fileSize?: number | null;
  downloadCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-runs".
 */
export interface SkillRun {
  id: string;
  runId?: string | null;
  user?: (string | null) | User;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  rerunOf?: (string | null) | SkillRun;
  rerunFromModel?: string | null;
  adapterProfile?: (string | null) | AdapterProfile;
  modelProfile?: (string | null) | ModelProfile;
  model?: string | null;
  modelVersion?: string | null;
  routeMode?: ('cheap' | 'quality' | 'fast' | 'balanced') | null;
  /**
   * 用户原始输入；普通用户只能经 /v1/runs?includeIO=1 审计导出。
   */
  inputJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 模型原始输出；普通用户只能经 /v1/runs?includeIO=1 审计导出。
   */
  outputText?: string | null;
  /**
   * 结构化输出原文；普通用户只能经 /v1/runs?includeIO=1 审计导出。
   */
  outputJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  promptTokens?: number | null;
  completionTokens?: number | null;
  totalTokens?: number | null;
  estimatedCost?: number | null;
  chargedAmount?: number | null;
  chargedCredits?: number | null;
  /**
   * 相比默认 premium 模型降低的估算成本；作为后台履约优化指标，不作为主叙事。
   */
  savedAmount?: number | null;
  latencyMs?: number | null;
  success?: boolean | null;
  errorCode?: string | null;
  formatValid?: boolean | null;
  /**
   * 对比/探测运行(skipAggregate)为 false，不计入 headline 指标，台账对账据此过滤
   */
  countedInMetrics?: boolean | null;
  /**
   * 内部排障句柄，不随用户私人台账或 Payload REST 直接返回。
   */
  newapiLogId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Skill × Model 的 prompt/schema/decoding/retry 适配补丁。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adapter-profiles".
 */
export interface AdapterProfile {
  id: string;
  title: string;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  sourceFailureCase?: (string | null) | FailureCase;
  modelProfile?: (string | null) | ModelProfile;
  modelName: string;
  modelVersion?: string | null;
  status?: ('draft' | 'active' | 'observed' | 'disabled') | null;
  reviewStatus?: ('pending' | 'needs_changes' | 'approved' | 'rejected') | null;
  reviewedBy?: (string | null) | User;
  reviewedAt?: string | null;
  reviewerNotes?: string | null;
  systemPromptAppend?: string | null;
  userPromptAppend?: string | null;
  outputSchemaPatch?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  decodingPatch?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  retryPolicy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  failureTypes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  liftScore?: number | null;
  beforeMetrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterMetrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  evidenceHash?: string | null;
  lastVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 从 CompatReports/SkillRuns 聚类出的脱敏失败知识库。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failure-cases".
 */
export interface FailureCase {
  id: string;
  title: string;
  profileKey?: string | null;
  errorType: string;
  modelName: string;
  primaryModelVersion?: string | null;
  skill?: (string | null) | Skill;
  skillVersion?: (string | null) | SkillVersion;
  symptom?: string | null;
  likelyCause?: string | null;
  triageStatus?: ('pending' | 'attributed' | 'needs_more_evidence' | 'verified') | null;
  rootCauseCategory?:
    | ('model_drift' | 'prompt_boundary' | 'schema_mismatch' | 'adapter_gap' | 'data_quality' | 'unknown')
    | null;
  triagedBy?: (string | null) | User;
  triagedAt?: string | null;
  triageNotes?: string | null;
  verificationCoverage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  repairTemplate?: string | null;
  verifyTemplate?: string | null;
  primaryInputBucket?: string | null;
  inputBuckets?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputBuckets?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  modelBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  modelVersions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  modelVersionBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  evidenceHash?: string | null;
  occurrenceCount?: number | null;
  affectedSkillCount?: number | null;
  status?: ('observed' | 'confirmed' | 'fixed' | 'ignored') | null;
  lastObservedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 模型的能力、价格、区域、常见失败和兼容证据 freshness。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-profiles".
 */
export interface ModelProfile {
  id: string;
  provider?: string | null;
  modelName: string;
  modelVersion?: string | null;
  profileStatus?: ('observed' | 'verified' | 'stale' | 'deprecated') | null;
  contextLength?: number | null;
  supportsStructuredOutput?: boolean | null;
  supportsToolUse?: boolean | null;
  chineseStyleScore?: number | null;
  jsonStabilityScore?: number | null;
  longOutputStabilityScore?: number | null;
  inputPrice?: number | null;
  outputPrice?: number | null;
  region?: string | null;
  platformPayAllowed?: boolean | null;
  knownIssues?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  regressionAlerts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  driftSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  driftHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  capabilities?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  freshness?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastObservedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bounties".
 */
export interface Bounty {
  id: string;
  title: string;
  description?: string | null;
  creator?: (string | null) | User;
  rewardType?: ('points' | 'cash' | 'credit') | null;
  rewardPoints?: number | null;
  rewardAmount?: number | null;
  status?: ('open' | 'accepted' | 'submitted' | 'completed' | 'disputed' | 'cancelled') | null;
  /**
   * 发布时从发布人冻结，完成后发给接单人
   */
  frozenPoints?: number | null;
  /**
   * 幂等键：防止重复提交导致重复发布/扣款
   */
  idempotencyKey?: string | null;
  acceptedBy?: (string | null) | User;
  submittedSkill?: (string | null) | Skill;
  requirements?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dueAt?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 本地模型兼容报告（系统接收，不含输入/输出原文）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compat-reports".
 */
export interface CompatReport {
  id: string;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  runner?: (string | null) | RunnerClient;
  anonymousUserHash?: string | null;
  modelProvider?: string | null;
  modelName?: string | null;
  modelProfile?: (string | null) | ModelProfile;
  adapterProfile?: (string | null) | AdapterProfile;
  benchmarkCase?: (string | null) | CompatTestCase;
  benchmarkScore?: number | null;
  benchmarkPassed?: boolean | null;
  modelVersion?: string | null;
  success?: boolean | null;
  latencyMs?: number | null;
  formatValid?: boolean | null;
  errorType?: string | null;
  inputSizeBucket?: string | null;
  outputSizeBucket?: string | null;
  runnerVersion?: string | null;
  /**
   * 被封禁用户的历史报告追溯降权：权重归 0、不进兼容分/可信榜
   */
  suppressed?: boolean | null;
  source?: ('community' | 'verified' | 'online' | 'benchmark') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runner-clients".
 */
export interface RunnerClient {
  id: string;
  user: string | User;
  runnerId: string;
  tokenHash?: string | null;
  /**
   * 旧版兼容字段；新令牌仅存 tokenHash，不再存明文
   */
  token?: string | null;
  tokenExpiresAt?: string | null;
  runnerVersion?: string | null;
  os?: string | null;
  arch?: string | null;
  label?: string | null;
  anonymousMode?: boolean | null;
  trustedLevel?: ('community' | 'verified') | null;
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 用于系统 benchmark 的 Skill 兼容测试样例。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compat-test-cases".
 */
export interface CompatTestCase {
  id: string;
  title: string;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  caseType?: ('normal' | 'edge' | 'long_context' | 'structured_output' | 'safety') | null;
  inputJson:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expectedOutputShape?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 如 ["title", "items.0.name"]；benchmark 会逐条检查。
   */
  requiredOutputPaths?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 字符串数组；适用于非 JSON 输出的黄金样例打分。
   */
  expectedTextIncludes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 0-1；低于该分数视为该黄金样例未达标。
   */
  minScore?: number | null;
  rubric?: string | null;
  enabled?: boolean | null;
  lastRunAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes".
 */
export interface InviteCode {
  id: string;
  code?: string | null;
  inviter?: (string | null) | User;
  usedBy?: (string | null) | User;
  status?: ('unused' | 'used' | 'expired' | 'revoked') | null;
  minLevelRequired?: number | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-logs".
 */
export interface ContributionLog {
  id: string;
  user: string | User;
  actionType:
    | 'skill_published'
    | 'skill_favorited'
    | 'skill_run'
    | 'skill_high_rating'
    | 'skill_version_update'
    | 'fix_issue'
    | 'eval_sample'
    | 'failure_case'
    | 'route_optimization'
    | 'compat_report'
    | 'review'
    | 'security'
    | 'bounty'
    | 'invite'
    | 'consume'
    | 'other';
  points: number;
  /**
   * 引发本次发放的用户（如收藏者/调用者），用于一次性奖励幂等去重
   */
  actor?: (string | null) | User;
  idempotencyKey?: string | null;
  relatedSkill?: (string | null) | Skill;
  relatedBounty?: (string | null) | Bounty;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-rules".
 */
export interface ContributionRule {
  id: string;
  actionType:
    | 'skill_published'
    | 'skill_favorited'
    | 'skill_run'
    | 'skill_high_rating'
    | 'skill_version_update'
    | 'fix_issue'
    | 'eval_sample'
    | 'failure_case'
    | 'route_optimization'
    | 'compat_report'
    | 'review'
    | 'security'
    | 'bounty'
    | 'invite'
    | 'consume'
    | 'other';
  basePoints: number;
  /**
   * 每用户每日该行为发放次数上限，0=不限
   */
  dailyLimit?: number | null;
  selfActionExcluded?: boolean | null;
  enabled?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-logs".
 */
export interface CreditLog {
  id: string;
  user: string | User;
  type: 'recharge' | 'exchange' | 'consume' | 'refund' | 'adjust';
  amount: number;
  balanceAfter?: number | null;
  idempotencyKey?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recharge-codes".
 */
export interface RechargeCode {
  id: string;
  /**
   * 仅展示前后缀，明文不会落库
   */
  codePreview?: string | null;
  codeHash?: string | null;
  /**
   * 仅创建/重置时填写；保存后立即转 HMAC，不保留明文
   */
  code?: string | null;
  creditAmount: number;
  status: 'unused' | 'used' | 'disabled';
  usedBy?: (string | null) | User;
  usedAt?: string | null;
  expiresAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  user?: (string | null) | User;
  skill: string | Skill;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-codes".
 */
export interface DeviceCode {
  id: string;
  deviceCode: string;
  userCode: string;
  status?: ('pending' | 'authorized' | 'denied' | 'consumed') | null;
  user?: (string | null) | User;
  runnerClient?: (string | null) | RunnerClient;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipHash?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-installs".
 */
export interface SkillInstall {
  id: string;
  user: string | User;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  runner?: (string | null) | RunnerClient;
  installedVersion?: string | null;
  installedChecksum?: string | null;
  status?: ('installed' | 'removed') | null;
  installedAt?: string | null;
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  user: string | User;
  type?:
    | (
        | 'skill_favorited'
        | 'skill_updated'
        | 'review'
        | 'bounty_accepted'
        | 'bounty_submitted'
        | 'bounty_completed'
        | 'system'
      )
    | null;
  title: string;
  body?: string | null;
  link?: string | null;
  read?: boolean | null;
  relatedSkill?: (string | null) | Skill;
  relatedBounty?: (string | null) | Bounty;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  skill: string | Skill;
  user?: (string | null) | User;
  rating?: number | null;
  content?: string | null;
  type?: ('review' | 'failure_case' | 'compat_report') | null;
  status?: ('visible' | 'hidden' | 'pending') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  reporter?: (string | null) | User;
  targetType: 'skill' | 'review' | 'user' | 'bounty';
  targetId: string;
  reason: 'spam' | 'low_quality' | 'copyright' | 'abuse' | 'security' | 'other';
  detail?: string | null;
  status?: ('open' | 'reviewing' | 'resolved' | 'dismissed') | null;
  handledBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-snapshots".
 */
export interface EvidenceSnapshot {
  id: string;
  targetType: 'skill_passport' | 'failure_case' | 'adapter_profile';
  targetId: string;
  evidenceHash: string;
  targetSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payloadHash?: string | null;
  keyId?: string | null;
  signature?: string | null;
  signedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  event: string;
  actor?: (string | null) | User;
  targetUser?: (string | null) | User;
  targetType?: string | null;
  targetId?: string | null;
  ipHash?: string | null;
  summary?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 企业/团队租户，Enterprise Registry 的隔离边界。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  name: string;
  slug: string;
  owner: string | User;
  plan?: ('team' | 'enterprise') | null;
  status?: ('active' | 'suspended') | null;
  modelAllowlist?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  policy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 企业身份治理骨架；企业管理员请走控制台身份策略面板，避免 REST 直接暴露 SCIM tokenDigest。
   */
  identityPolicy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 组织成员、角色与状态，用于 Enterprise Registry 运行授权。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-members".
 */
export interface OrganizationMember {
  id: string;
  organization: string | Organization;
  user: string | User;
  role?: ('member' | 'approver' | 'auditor' | 'admin') | null;
  status?: ('active' | 'suspended') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 企业 AI Skill 注册表：审批、版本锁定、模型白名单与审计治理入口。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-registries".
 */
export interface EnterpriseRegistry {
  id: string;
  name: string;
  organization: string | Organization;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  passport?: (string | null) | SkillPassport;
  approvalStatus?: ('pending' | 'approved' | 'restricted' | 'disabled' | 'deprecated') | null;
  approvedBy?: (string | null) | User;
  approvedAt?: string | null;
  modelAllowlist?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  usageScope?: string | null;
  riskNotes?: string | null;
  auditPolicy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 批准时冻结 Contract/Passport/证书摘要，用于后续版本漂移和重新审批判断。
   */
  adoptionBaseline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 企业 Skill 运行与策略拒绝的审计台账；不含输入/输出原文。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-audit-logs".
 */
export interface EnterpriseAuditLog {
  id: string;
  organization: string | Organization;
  registry?: (string | null) | EnterpriseRegistry;
  actor?: (string | null) | User;
  skill: string | Skill;
  skillVersion?: (string | null) | SkillVersion;
  skillRun?: (string | null) | SkillRun;
  runId: string;
  modelName?: string | null;
  modelVersion?: string | null;
  modelProfile?: (string | null) | ModelProfile;
  outcome: 'success' | 'failed' | 'denied';
  errorCode?: string | null;
  policyReason?: string | null;
  inputSizeBucket?: string | null;
  outputSizeBucket?: string | null;
  latencyMs?: number | null;
  estimatedCost?: number | null;
  chargedCredits?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-price-snapshots".
 */
export interface ModelPriceSnapshot {
  id: string;
  model: string;
  inputPrice: number;
  outputPrice: number;
  currency?: string | null;
  sourceUrl?: string | null;
  capturedAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "score-snapshots".
 */
export interface ScoreSnapshot {
  id: string;
  skill: string | Skill;
  localScore: number;
  reportCount?: number | null;
  payloadHash?: string | null;
  keyId?: string | null;
  signature?: string | null;
  signedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'skill-versions';
        value: string | SkillVersion;
      } | null)
    | ({
        relationTo: 'skill-passports';
        value: string | SkillPassport;
      } | null)
    | ({
        relationTo: 'skill-artifacts';
        value: string | SkillArtifact;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'skill-runs';
        value: string | SkillRun;
      } | null)
    | ({
        relationTo: 'bounties';
        value: string | Bounty;
      } | null)
    | ({
        relationTo: 'compat-reports';
        value: string | CompatReport;
      } | null)
    | ({
        relationTo: 'compat-test-cases';
        value: string | CompatTestCase;
      } | null)
    | ({
        relationTo: 'adapter-profiles';
        value: string | AdapterProfile;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'invite-codes';
        value: string | InviteCode;
      } | null)
    | ({
        relationTo: 'contribution-logs';
        value: string | ContributionLog;
      } | null)
    | ({
        relationTo: 'contribution-rules';
        value: string | ContributionRule;
      } | null)
    | ({
        relationTo: 'credit-logs';
        value: string | CreditLog;
      } | null)
    | ({
        relationTo: 'recharge-codes';
        value: string | RechargeCode;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'runner-clients';
        value: string | RunnerClient;
      } | null)
    | ({
        relationTo: 'device-codes';
        value: string | DeviceCode;
      } | null)
    | ({
        relationTo: 'skill-installs';
        value: string | SkillInstall;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'failure-cases';
        value: string | FailureCase;
      } | null)
    | ({
        relationTo: 'evidence-snapshots';
        value: string | EvidenceSnapshot;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'organization-members';
        value: string | OrganizationMember;
      } | null)
    | ({
        relationTo: 'enterprise-registries';
        value: string | EnterpriseRegistry;
      } | null)
    | ({
        relationTo: 'enterprise-audit-logs';
        value: string | EnterpriseAuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'model-profiles';
        value: string | ModelProfile;
      } | null)
    | ({
        relationTo: 'model-price-snapshots';
        value: string | ModelPriceSnapshot;
      } | null)
    | ({
        relationTo: 'score-snapshots';
        value: string | ScoreSnapshot;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  clientSubmissionKey?: T;
  category?: T;
  importSourceFormat?: T;
  importSourceLocator?: T;
  importSourceHash?: T;
  importSourceLastSyncedAt?: T;
  importSourceLastDiff?: T;
  author?: T;
  forkedFrom?: T;
  visibility?: T;
  status?: T;
  currentVersion?: T;
  isOfficial?: T;
  isEssential?: T;
  essentialReason?: T;
  isFeatured?: T;
  isFreeleech?: T;
  skillRank?: T;
  localScore?: T;
  healthScore?: T;
  runCount?: T;
  downloadCount?: T;
  favoriteCount?: T;
  reviewCount?: T;
  avgRating?: T;
  avgCost?: T;
  avgLatencyMs?: T;
  successRate?: T;
  formatSuccessRate?: T;
  lastRunAt?: T;
  lastUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions_select".
 */
export interface SkillVersionsSelect<T extends boolean = true> {
  skill?: T;
  version?: T;
  systemPrompt?: T;
  promptTemplate?: T;
  inputSchema?: T;
  outputSchema?: T;
  recommendedModels?: T;
  routePolicy?: T;
  changelog?: T;
  contractHash?: T;
  contractStatus?: T;
  license?: T;
  minRunnerVersion?: T;
  permissions?:
    | T
    | {
        network?: T;
        fileRead?: T;
        fileWrite?: T;
        shell?: T;
      };
  examples?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-passports_select".
 */
export interface SkillPassportsSelect<T extends boolean = true> {
  title?: T;
  skill?: T;
  skillVersion?: T;
  status?: T;
  skillClass?: T;
  trustScore?: T;
  signatureStatus?: T;
  manifestChecksum?: T;
  capabilitySummary?: T;
  compatibilitySummary?: T;
  reliabilitySummary?: T;
  safetySummary?: T;
  failureSummary?: T;
  evidenceSummary?: T;
  evidenceHash?: T;
  enterpriseSummary?: T;
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-artifacts_select".
 */
export interface SkillArtifactsSelect<T extends boolean = true> {
  skill?: T;
  skillVersion?: T;
  version?: T;
  format?: T;
  manifest?: T;
  checksum?: T;
  fileSize?: T;
  downloadCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-runs_select".
 */
export interface SkillRunsSelect<T extends boolean = true> {
  runId?: T;
  user?: T;
  skill?: T;
  skillVersion?: T;
  rerunOf?: T;
  rerunFromModel?: T;
  adapterProfile?: T;
  modelProfile?: T;
  model?: T;
  modelVersion?: T;
  routeMode?: T;
  inputJson?: T;
  outputText?: T;
  outputJson?: T;
  promptTokens?: T;
  completionTokens?: T;
  totalTokens?: T;
  estimatedCost?: T;
  chargedAmount?: T;
  chargedCredits?: T;
  savedAmount?: T;
  latencyMs?: T;
  success?: T;
  errorCode?: T;
  formatValid?: T;
  countedInMetrics?: T;
  newapiLogId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bounties_select".
 */
export interface BountiesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  creator?: T;
  rewardType?: T;
  rewardPoints?: T;
  rewardAmount?: T;
  status?: T;
  frozenPoints?: T;
  idempotencyKey?: T;
  acceptedBy?: T;
  submittedSkill?: T;
  requirements?: T;
  dueAt?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compat-reports_select".
 */
export interface CompatReportsSelect<T extends boolean = true> {
  skill?: T;
  skillVersion?: T;
  runner?: T;
  anonymousUserHash?: T;
  modelProvider?: T;
  modelName?: T;
  modelProfile?: T;
  adapterProfile?: T;
  benchmarkCase?: T;
  benchmarkScore?: T;
  benchmarkPassed?: T;
  modelVersion?: T;
  success?: T;
  latencyMs?: T;
  formatValid?: T;
  errorType?: T;
  inputSizeBucket?: T;
  outputSizeBucket?: T;
  runnerVersion?: T;
  suppressed?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compat-test-cases_select".
 */
export interface CompatTestCasesSelect<T extends boolean = true> {
  title?: T;
  skill?: T;
  skillVersion?: T;
  caseType?: T;
  inputJson?: T;
  expectedOutputShape?: T;
  requiredOutputPaths?: T;
  expectedTextIncludes?: T;
  minScore?: T;
  rubric?: T;
  enabled?: T;
  lastRunAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adapter-profiles_select".
 */
export interface AdapterProfilesSelect<T extends boolean = true> {
  title?: T;
  skill?: T;
  skillVersion?: T;
  sourceFailureCase?: T;
  modelProfile?: T;
  modelName?: T;
  modelVersion?: T;
  status?: T;
  reviewStatus?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  reviewerNotes?: T;
  systemPromptAppend?: T;
  userPromptAppend?: T;
  outputSchemaPatch?: T;
  decodingPatch?: T;
  retryPolicy?: T;
  failureTypes?: T;
  liftScore?: T;
  beforeMetrics?: T;
  afterMetrics?: T;
  evidenceHash?: T;
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  role?: T;
  level?: T;
  accountStatus?: T;
  contributionScore?: T;
  consumptionScore?: T;
  creditBalance?: T;
  ratioScore?: T;
  inviteCount?: T;
  warningCount?: T;
  bio?: T;
  invitedBy?: T;
  ipHash?: T;
  deviceHash?: T;
  newapiUserId?: T;
  newapiKeyEncrypted?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes_select".
 */
export interface InviteCodesSelect<T extends boolean = true> {
  code?: T;
  inviter?: T;
  usedBy?: T;
  status?: T;
  minLevelRequired?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-logs_select".
 */
export interface ContributionLogsSelect<T extends boolean = true> {
  user?: T;
  actionType?: T;
  points?: T;
  actor?: T;
  idempotencyKey?: T;
  relatedSkill?: T;
  relatedBounty?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contribution-rules_select".
 */
export interface ContributionRulesSelect<T extends boolean = true> {
  actionType?: T;
  basePoints?: T;
  dailyLimit?: T;
  selfActionExcluded?: T;
  enabled?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-logs_select".
 */
export interface CreditLogsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  amount?: T;
  balanceAfter?: T;
  idempotencyKey?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recharge-codes_select".
 */
export interface RechargeCodesSelect<T extends boolean = true> {
  codePreview?: T;
  codeHash?: T;
  code?: T;
  creditAmount?: T;
  status?: T;
  usedBy?: T;
  usedAt?: T;
  expiresAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  skill?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runner-clients_select".
 */
export interface RunnerClientsSelect<T extends boolean = true> {
  user?: T;
  runnerId?: T;
  tokenHash?: T;
  token?: T;
  tokenExpiresAt?: T;
  runnerVersion?: T;
  os?: T;
  arch?: T;
  label?: T;
  anonymousMode?: T;
  trustedLevel?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-codes_select".
 */
export interface DeviceCodesSelect<T extends boolean = true> {
  deviceCode?: T;
  userCode?: T;
  status?: T;
  user?: T;
  runnerClient?: T;
  meta?: T;
  ipHash?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-installs_select".
 */
export interface SkillInstallsSelect<T extends boolean = true> {
  user?: T;
  skill?: T;
  skillVersion?: T;
  runner?: T;
  installedVersion?: T;
  installedChecksum?: T;
  status?: T;
  installedAt?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  body?: T;
  link?: T;
  read?: T;
  relatedSkill?: T;
  relatedBounty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  skill?: T;
  user?: T;
  rating?: T;
  content?: T;
  type?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  detail?: T;
  status?: T;
  handledBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failure-cases_select".
 */
export interface FailureCasesSelect<T extends boolean = true> {
  title?: T;
  profileKey?: T;
  errorType?: T;
  modelName?: T;
  primaryModelVersion?: T;
  skill?: T;
  skillVersion?: T;
  symptom?: T;
  likelyCause?: T;
  triageStatus?: T;
  rootCauseCategory?: T;
  triagedBy?: T;
  triagedAt?: T;
  triageNotes?: T;
  verificationCoverage?: T;
  repairTemplate?: T;
  verifyTemplate?: T;
  primaryInputBucket?: T;
  inputBuckets?: T;
  outputBuckets?: T;
  modelBreakdown?: T;
  modelVersions?: T;
  modelVersionBreakdown?: T;
  sourceBreakdown?: T;
  evidenceHash?: T;
  occurrenceCount?: T;
  affectedSkillCount?: T;
  status?: T;
  lastObservedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-snapshots_select".
 */
export interface EvidenceSnapshotsSelect<T extends boolean = true> {
  targetType?: T;
  targetId?: T;
  evidenceHash?: T;
  targetSummary?: T;
  payloadHash?: T;
  keyId?: T;
  signature?: T;
  signedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  event?: T;
  actor?: T;
  targetUser?: T;
  targetType?: T;
  targetId?: T;
  ipHash?: T;
  summary?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  owner?: T;
  plan?: T;
  status?: T;
  modelAllowlist?: T;
  policy?: T;
  identityPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-members_select".
 */
export interface OrganizationMembersSelect<T extends boolean = true> {
  organization?: T;
  user?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-registries_select".
 */
export interface EnterpriseRegistriesSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  skill?: T;
  skillVersion?: T;
  passport?: T;
  approvalStatus?: T;
  approvedBy?: T;
  approvedAt?: T;
  modelAllowlist?: T;
  usageScope?: T;
  riskNotes?: T;
  auditPolicy?: T;
  adoptionBaseline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-audit-logs_select".
 */
export interface EnterpriseAuditLogsSelect<T extends boolean = true> {
  organization?: T;
  registry?: T;
  actor?: T;
  skill?: T;
  skillVersion?: T;
  skillRun?: T;
  runId?: T;
  modelName?: T;
  modelVersion?: T;
  modelProfile?: T;
  outcome?: T;
  errorCode?: T;
  policyReason?: T;
  inputSizeBucket?: T;
  outputSizeBucket?: T;
  latencyMs?: T;
  estimatedCost?: T;
  chargedCredits?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-profiles_select".
 */
export interface ModelProfilesSelect<T extends boolean = true> {
  provider?: T;
  modelName?: T;
  modelVersion?: T;
  profileStatus?: T;
  contextLength?: T;
  supportsStructuredOutput?: T;
  supportsToolUse?: T;
  chineseStyleScore?: T;
  jsonStabilityScore?: T;
  longOutputStabilityScore?: T;
  inputPrice?: T;
  outputPrice?: T;
  region?: T;
  platformPayAllowed?: T;
  knownIssues?: T;
  regressionAlerts?: T;
  driftSummary?: T;
  driftHistory?: T;
  capabilities?: T;
  freshness?: T;
  lastObservedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-price-snapshots_select".
 */
export interface ModelPriceSnapshotsSelect<T extends boolean = true> {
  model?: T;
  inputPrice?: T;
  outputPrice?: T;
  currency?: T;
  sourceUrl?: T;
  capturedAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "score-snapshots_select".
 */
export interface ScoreSnapshotsSelect<T extends boolean = true> {
  skill?: T;
  localScore?: T;
  reportCount?: T;
  payloadHash?: T;
  keyId?: T;
  signature?: T;
  signedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  slogan?: string | null;
  featuredSkills?: (string | Skill)[] | null;
  /**
   * 后台配置新用户第一跑 Skill 包：排序、推荐理由和公开默认示例。为空时回退 Skill 自身 isEssential/essentialReason。
   */
  essentialStarterPack?:
    | {
        skill: string | Skill;
        order?: number | null;
        reason?: string | null;
        /**
         * 给新用户试跑的公开示例对象；不要填写真实客户输入。
         */
        starterExample?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 开启时注册页要求填写邮箱；关闭时用户可不填，系统会生成内部占位邮箱用于账号登录态。
   */
  registrationEmailRequired?: boolean | null;
  announcement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-settings".
 */
export interface EconomySetting {
  id: string;
  exchangeEnabled?: boolean | null;
  /**
   * 新用户注册即送的试用额度（营销成本，§7A 建议 30-50）。0=不送。赠送的 credit 只能消耗，不产生贡献值
   */
  freeCreditOnRegister?: number | null;
  alpha?: number | null;
  /**
   * 接入 New API /api/log 自动回填前手动填；0 = 兑换池空、自动关闭兑换。1 分 = 1 credit
   */
  monthlyRealizedMarginCents?: number | null;
  /**
   * newapi=/api/log 真值；local=本平台 consume 流水估算；manual=手填占位，不允许开放兑换
   */
  marginSource?: ('manual' | 'newapi' | 'local') | null;
  /**
   * 由 worker:reconcile-newapi 写入；必须是本月对账，兑换开关才生效
   */
  marginReconciledAt?: string | null;
  pointsPerCredit?: number | null;
  minCreditPerTx?: number | null;
  perTxMaxCredit?: number | null;
  perUserDailyMaxCredit?: number | null;
  perUserMonthlyMaxCredit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 部署后由管理员配置模型网关、New API、签名与备份状态；容器启动只依赖数据库和 PAYLOAD_SECRET。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployment-settings".
 */
export interface DeploymentSetting {
  id: string;
  /**
   * 例如 https://gewu.example.com；NAS 内网试跑可用 http://NAS_IP:8787。
   */
  serverUrl?: string | null;
  /**
   * 通常与服务端公网地址同源；正式生产预检会阻断不同源。
   */
  publicServerUrl?: string | null;
  /**
   * NAS/内网直连通常填 0；Nginx/群晖反代 append XFF 时通常填 1。
   */
  trustedProxyCount?: number | null;
  modelGatewayBaseUrl?: string | null;
  /**
   * 可粘贴明文；保存时自动 AES-GCM 加密。留空表示暂不启用平台真实调用。
   */
  modelGatewayKeyEncrypted?: string | null;
  modelGatewayDefaultModel?: string | null;
  /**
   * 逗号分隔；留空使用系统默认国产模型白名单。
   */
  approvedPlatformModels?: string | null;
  runRateLimitPerMin?: number | null;
  benchmarkQueueMaxJobs?: number | null;
  benchmarkMaxAttemptsPerSkill?: number | null;
  benchmarkModels?: string | null;
  newapiAdminBaseUrl?: string | null;
  /**
   * 填系统访问令牌，不是模型 sk-* Key；保存时自动加密。
   */
  newapiAdminKeyEncrypted?: string | null;
  newapiAdminUserId?: string | null;
  newapiAuthBearer?: boolean | null;
  newapiSubGroup?: string | null;
  /**
   * 不推荐；仅在确认默认分组低价且受限时打开。
   */
  allowDefaultNewapiSubGroup?: boolean | null;
  newapiCreditToQuota?: number | null;
  newapiSubTokenTtlDays?: number | null;
  newapiUsageSource?: ('newapi' | 'local') | null;
  newapiLogScope?: ('auto' | 'admin' | 'self') | null;
  newapiMarginRate?: number | null;
  newapiModelMarginRates?: string | null;
  newapiReconcileToleranceCents?: number | null;
  newapiUsdExchangeRateCny?: number | null;
  allowLocalMarginExchange?: boolean | null;
  /**
   * ed25519 PKCS8 base64；可用 npm run keygen 生成，保存时自动加密。
   */
  signingKeyEncrypted?: string | null;
  backupEncryptionConfirmed?: boolean | null;
  backupOffsiteConfirmed?: boolean | null;
  backupRestoreDrillAt?: string | null;
  backupNotes?: string | null;
  /**
   * 逗号分隔；格式 target|urlPrefix 或 urlPrefix。用于 /v1/anchors/verify 判断 publishedTo 是否命中可信网络。
   */
  anchorTrustedPublishers?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  slogan?: T;
  featuredSkills?: T;
  essentialStarterPack?:
    | T
    | {
        skill?: T;
        order?: T;
        reason?: T;
        starterExample?: T;
        id?: T;
      };
  registrationEmailRequired?: T;
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-settings_select".
 */
export interface EconomySettingsSelect<T extends boolean = true> {
  exchangeEnabled?: T;
  freeCreditOnRegister?: T;
  alpha?: T;
  monthlyRealizedMarginCents?: T;
  marginSource?: T;
  marginReconciledAt?: T;
  pointsPerCredit?: T;
  minCreditPerTx?: T;
  perTxMaxCredit?: T;
  perUserDailyMaxCredit?: T;
  perUserMonthlyMaxCredit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployment-settings_select".
 */
export interface DeploymentSettingsSelect<T extends boolean = true> {
  serverUrl?: T;
  publicServerUrl?: T;
  trustedProxyCount?: T;
  modelGatewayBaseUrl?: T;
  modelGatewayKeyEncrypted?: T;
  modelGatewayDefaultModel?: T;
  approvedPlatformModels?: T;
  runRateLimitPerMin?: T;
  benchmarkQueueMaxJobs?: T;
  benchmarkMaxAttemptsPerSkill?: T;
  benchmarkModels?: T;
  newapiAdminBaseUrl?: T;
  newapiAdminKeyEncrypted?: T;
  newapiAdminUserId?: T;
  newapiAuthBearer?: T;
  newapiSubGroup?: T;
  allowDefaultNewapiSubGroup?: T;
  newapiCreditToQuota?: T;
  newapiSubTokenTtlDays?: T;
  newapiUsageSource?: T;
  newapiLogScope?: T;
  newapiMarginRate?: T;
  newapiModelMarginRates?: T;
  newapiReconcileToleranceCents?: T;
  newapiUsdExchangeRateCny?: T;
  allowLocalMarginExchange?: T;
  signingKeyEncrypted?: T;
  backupEncryptionConfirmed?: T;
  backupOffsiteConfirmed?: T;
  backupRestoreDrillAt?: T;
  backupNotes?: T;
  anchorTrustedPublishers?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
